openapi: "3.0.3"

info:
  title: API for coding exercise
  description: coding exercise API definition
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: Optional server description, e.g. Main (production) server
paths:
  /calculateOccupancyWithPrice:
    get:
      operationId: occupancyPriceGet
      tags:
        - occupancy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculateOccupancyPriceRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateOccupancyPriceResponse'
        400:
          description: bad request

components:
  schemas:

    CalculateOccupancyPriceRequest:
      type: object
      required: [freeEconomyRooms, freePremiumRooms, customerData]
      properties:
        freeEconomyRooms:
          type: integer
          minimum: 0
        freePremiumRooms:
          type: integer
          minimum: 0
        customerData:
          type: array
          items:
            type: number
            minimum: 0
            exclusiveMinimum: true # not for free!
            format: float

    CalculateOccupancyPriceResponse:
      type: object
      properties:
        usageEconomy:
          type: integer
        usagePremium:
          type: integer
        pricePremium:
          type: number
          format: float
        priceEconomy:
          type: number
          format: float